import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { UiHeader } from "@/shared";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["400", "700", "100", "300", "500", "900"],
  style: ["normal", "italic"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <UiHeader />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
